from ursina import Vec3

CENTAUR_STATS = {'name': 'Centaur',
                 'health': 10,
                 'damage': 2,
                 'worth':1,
                 'speed':200,
                 'sight':10,
                 'closeness':2.2,
                 'attack_speed': 1,
                 'scale': Vec3(0.02,0.024,0.015),
                 'boss_scale':Vec3(0.015,0.02,0.015),
                 'boss_rotation': 0,
                 'boss_speed':200,
                 'boss_sight':15,
                 'boss_closeness':2}

BASILISK_STATS = {'name': 'Basilisk',
                'health': 200,
                'damage': 20,
                'worth':10,
                'speed':35000,
                'sight':15,
                'closeness': 5.5,
                'attack_speed': 1,
                'scale': Vec3(0.0001,0.0002,0.0001),
                'boss_scale':Vec3(2,6,2),
                'boss_rotation': 90,
                'boss_speed':3,
                'boss_sight':20,
                'boss_closeness':10}

GORGON_STATS = {'name': 'Gorgon',
                'health': 3000,
                'damage': 300,
                'worth':40,
                'speed':400,
                'sight':12,
                'closeness':2.5,
                'attack_speed': 1,
                'scale': Vec3(0.01,0.02,0.01),
                'boss_scale':0.05,
                'boss_rotation': 0,
                'boss_speed':50,
                'boss_sight':20,
                'boss_closeness':3}

CHIMERA_STATS = {'name': 'Chimera',
                'health': 10000,
                'damage': 1000,
                'worth':100,
                'speed':800,
                'sight':15,
                'closeness':2.5,
                'attack_speed': 1,
                'scale': Vec3(0.005,0.01,0.005),
                'boss_scale':0.005,
                'boss_rotation': 0,
                'boss_speed':1400,
                'boss_sight':20,
                'boss_closeness':5}